<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.0-beta</Version>
    <FileVersion>0.1.0.0</FileVersion>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <Authors>oscer</Authors>
    <Title>Tool Kit</Title>
    <AssemblyName>ToolKit</AssemblyName>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
  </ItemGroup>

</Project>